### ISSUE TITLE
IRODS ingestion of gantry data (continue 03)

### ISSUE THREAD

**Issue by julianpistorius** [AgPipeline/computing-pipeline#116]
Continuation of https://github.com/AgPipeline/issues-and-projects/issues/93

**Task to do**

Set up and document an automated process for ingesting gantry data into CyVerse Data Store (IRODS)

**Reason**

- [ ] Ease of access from VICE (for workbench/data exploration)
- [ ] Close to CyVerse & UA computational resources

**Result**

- Scripts and configuration necessary for setting this up
- Document (as text file in the code repository where the automation & logic end up)
- Monitoring & alerting (at least documenting what success/failure looks like)

**Steps to take**

- [ ] Ensure tar file creation & `irsync` work reliably (or fail noisily)

**Comment by julianpistorius** [comment]
Needs to be closed or moved to another organization.
