### ISSUE TITLE
OLS Weeks 11-12

### ISSUE THREAD

**Issue by MagicMilly** [AgPipeline/computing-pipeline#118]
- [x] Turn this issue into epic and create 2-3 issues under it for pipeline documentation (user stories, home page links, where to start depending on level of use)

Meetings: 
- [x] Cohort call
- [x] Mentor call

Assignments: 
- [x] Read [document](https://docs.google.com/document/d/1U7kIwSyPRpovVLVIvKRcuuh9wNQBHQQZC3KSwP7kbxs/edit?usp=sharing) on unconscious bias and think of ways to implement this info in our team / projects
- [x] Create a [Persona & Pathway](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/bring-on-contributors-using-personas-and-pathways/) for our project 
- [x] Each of us complete [mid-program survey](https://docs.google.com/forms/d/e/1FAIpQLSfpmeiQMqUNI4xvj9DiScYUN-qvIUQ2q6A0V94umm6M2M-FsQ/viewform)

**Comment by KristinaRiemer** [comment]
~~Determine if @dlebauer completed survey.~~ He had!
