### ISSUE TITLE
Fix TravisCI integration for template-transformer-simple/test-development branch

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#126]
**Task to do**
TravisCI is currently failing due to various errors that need to be resolved before merging branch

**Reason**
The purpose of the branch is TravisCI integration, so it need to work

**Result**
TravisCI integration successfully performs pylint and unit test

**Steps to take**
1.  Build Docker container for testing
  - [ ] After `rm -r test-files/` step, run `generate_docker.py` script to generate Dockerfile
  - [ ] Build Docker image for testing
2. Run Pylint
- [ ] Run PyLint in Docker container against the .py files (see .travis.yml file for hints)
3. Run Pytest
- [ ] Run Pytest testing script in Docker container

Other:
- [ ] Change "git clone" to "git pull" in for pulling the pylint.rc file

**Comment by Chris-Schnaufer** [comment]
Closing this due to new GitHub actions feature
