### ISSUE TITLE
Resolve TravisCI errors for ua-gantry-environment/test-development

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#127]
**Task to do**
TravisCI is generating errors that need to be resolved

**Reason**
The purpose of this branch is to run TravisCI integration, resolving these errors will allow the code to be tested

**Result**
TravisCI will successfully run pylint and pytest on the code bases

**Steps to take**
1. Common-Image matrix path in .travis.yml
- [ ] Ensure `pyclowder` python library is installed in built Docker image (It's OK if all matrix paths have this installed, whatever is cleanest)
- [ ] Successfully run pylint against the .py files in Docker image
- [ ] Successfully run pytest in Docker image
2. RGB-plot-base matrix path in .travis.yml
- [ ] Ensure pytest is installed
- [ ] Successfully run pylint against the .py files in Docker image
- [ ] Successfully run pytest in Docker image
3. Lidar-plot-base matrix path in .travis.yml
- [ ] Ensure `liblas` python library is installed in built Docker image (this can also be installed for every matrix path)
- [ ] Successfully run pylint against the .py files in Docker image
- [ ] Successfully run pytest in Docker image

**Comment by Chris-Schnaufer** [comment]
Closing this due to new GitHub actions feature
