### ISSUE TITLE
OLS Weeks 13-14

### ISSUE THREAD

**Issue by MagicMilly** [AgPipeline/computing-pipeline#131]
**Assignments**
- [x] Meet with Chris again 
  - [x] Roadmap releases
  - [x] Have him add links (see issue)
  - [x] Discuss personas
  - [x] List of technical tools/skills needed to work with pipeline
- [ ] Review Mountain of Engagement [assignment](https://docs.google.com/document/d/1X2-oXvq5ET30-hCcgWEG5iLvv9FbAiuEgXuVY5hle8o/edit?usp=sharing) as a group
- [x] Meet with Katrin (last mentor call)
- [x] Attend cohort call (social)
- [ ] Put personas content on OSF wiki

**Future to-dos**
- [ ] Prepare presentation
- [ ] Complete report

**Comment by KristinaRiemer** [comment]
From meeting with Chris: 
- [ ] Add OSF page for roadmap release details
    - Is the roadmap a working document?
    - Definitions of releases
- [ ] Add personas to OSF home page
- [ ] Checklists of tools (with links, brief summary) for each persona

**Comment by Chris-Schnaufer** [comment]
@MagicMilly @KristinaRiemer Move OLS undone items to new issue #136
