### ISSUE TITLE
Nomad job for PEcAn docker-develop branch, Part 2

### ISSUE THREAD

**Issue by julianpistorius** [AgPipeline/computing-pipeline#155]
Follow-on from https://github.com/AgPipeline/issues-and-projects/issues/150

Now that I have working docker-compose setup:

**Task to do**

- [ ] Create a Nomad job

**Reason**

We need a robust, automatically deployable replacement for servers like Welsch

**Result**

A Nomad job that when run on a Nomad cluster will result in a robust, fault-tolerant set of services which can be used for DARPA model development

**Steps**

- [ ] Create a GitHub project with sub-tasks
- [ ] Take it service by service, starting with the most persistent ones.

**Comment by dlebauer** [comment]
obsolete, or at least not high priority
