### ISSUE TITLE
Update PR issue w/ checklist of desired feedback and timeframe from a PR

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#162]
Add a checklist to make it easier for reviewers to indicate how they want a PR reviewed and when. For example:
```
Focus of Pull Request:
All comments are welcome regardless of which items are checked off.
- [ ] All of the below (no need to check off the other boxes)
- [ ] There are no errors or inconsistencies
- [ ] Everything appears clear and easy to understand
- [ ] Suggest improvements
- [ ] Identify areas where functionality and/or documentation is missing

Time frame for completing Pull Request review (from creation date):
- [ ] As soon as possible
- [ ] In the next two weeks
- [ ] In the next month
```

**Comment by Chris-Schnaufer** [comment]
https://github.com/AgPipeline/.github/pull/6
