### ISSUE TITLE
Have SciF "clean" app use makeflow cleaning feature

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#165]
**Task to do**
The clean app in the SciF Docker image should use makeflow for cleanup as much as possible. Implement that ability

**Reason**
Makeflow has the ability to clean up its environment and produced results.

**Result**
Makeflow is not only used to perform the desired processing, but can clean up after itself as well

**Steps to take**
- [x] Investigate what it will take to have makeflow perform a clean up regardless of the workflow app used (with or without ODM at this time)
- [x] Make needed changes to allow makeflow to clean up
- [x] Build SciF Docker image with changes
- [x] (optional) run the new SciF docker image to generate folders and files to cleanup
- [x] Run SciF Docker image "clean" app to cleanup after a run

**Comment by Chris-Schnaufer** [comment]
See conversation with Julian: https://github.com/AgPipeline/drone-makeflow/pull/4/files#r467247276

**Comment by Chris-Schnaufer** [comment]
Waiting for scif_odm PR to complete before making additional ones

**Comment by Chris-Schnaufer** [comment]
PR: https://github.com/AgPipeline/drone-makeflow/pull/9
