### ISSUE TITLE
Create TERRA REF Season 6 SQLite database

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#173]
**Task to do**
Create a single Season 6 SQLite database

**Reason**
Having a database for refined searching can be useful for easy file discovery

**Result**
A single SQLite database for Season 6 data

Due to limitations on using Globus and the TERRA REF Workbench, it's only possible to create about 1 weeks worth of data per SQLite database. This requires the following approach:
**Steps to take**
- [x] Generate multiple SQLite databases each containing about 1 week's worth of data
- [x] Investigate merging multiple SQLite databases into 1 large database containing all Season 6 data
- [x] Perform the merge

While it's expected that it should be possible to merge all the SQLite databases into a single database, there may be compute resource constraints on accomplishing that. The fall back position, that's less than desirable, is to document how users can use SQLite capabilities to tie multiple databases together for the purposes of making queries (this is existing functionality)

**Comment by Chris-Schnaufer** [comment]
This is follow on work for issue https://app.zenhub.com/workspaces/ua-ag-data-science-5a57a3198339f11ba1c85775/issues/agpipeline/issues-and-projects/146

**Comment by Chris-Schnaufer** [comment]
The database is available at: https://drive.google.com/file/d/10H4P5ZQNpWBNCtqkv8jUJelw_ZjIboi2/view?usp=sharing

**Comment by Chris-Schnaufer** [comment]
Created new issue for feedback: https://github.com/AgPipeline/issues-and-projects/issues/192
