### ISSUE TITLE
Find shell script linter and style guide for CI

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#178]
**Task to do**
Have a shell lint checker and style guide that can be CI integrated

**Reason**
Having shell scripts checked that they conform within a certain tolerance via CI will help with code soundness and stability

**Result**
Shell scripts pass a linter for PRs, and main and develop branch pushes, using CI

Criteria for linter:
- accurately flags problems (doesn't incorrectly flag shell code)
- provides override mechanism for script code checking (code would flag error, but check can be overridden)
- source project is actively being worked on
- wide adaptation
- integrates with GitHub CI (Workflows and Actions)

**Steps to take**
- [x] Survey what's available and make a determination of what to use
- [x] Define acceptance criteria (how much error/warning is permitted)
- [ ] Make tool and criteria available to developers
- [ ] Provide GitHub CI integration file(s)

**Comment by Chris-Schnaufer** [comment]
A possibility is https://plugins.jetbrains.com/plugin/10195-shellcheck (recommended by Ken and Julian)

**Comment by dlebauer** [comment]
I think it was Ken who also recommended https://github.com/github/super-linter - although perhaps it only works as a github action? In any case, for shell it uses shellcheck recommended above

**Comment by Chris-Schnaufer** [comment]
Looking over what's available, I believe using what GitHub uses `shellcheck` is probably a good bet: https://docs.gitlab.com/ee/development/shell_scripting_guide/.

They're using shellcheck: https://www.shellcheck.net/

Also GitHub recommended is to use `shfmt` to https://github.com/mvdan/sh#shfmt with Google Coding Style: https://google.github.io/styleguide/shellguide.html. This needs to be added to the scope of this issue

**Comment by Chris-Schnaufer** [comment]
drone-makeflow: https://github.com/AgPipeline/drone-makeflow/pull/25
Contributing documentation: https://github.com/AgPipeline/.github/pull/11
