### ISSUE TITLE
Rename entrypoint() function to begin_process() in AgPypeline library

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#188]
**Task to do**
Rename the entrypoint() function to begin_process() in `entrypoint.py` file in AgPypeline library

**Reason**
It is confusing that the function name called to start processing is the same name as the Python module.

**Result**
The function is renamed.

**Other**
It might be better to keep the `entrypoint()` name; move the functionality into `begin_process()` and have the now-empty entrypoint() function call begin_process(). This will lower the burden of the rename by allowing library users to transition over a period of time

**Developer Notes**
- [ ] ~Ensure all repositories using AgPypeline are installing versioned libraries. Eg: `agpypeline==0.0.32`. See #203~
- [ ] ~Integration test (manually or otherwise) all repositories that are updated~
- [ ] ~Make the AgPypeline change~
- [ ] ~Write another issue regarding updating repositories using AgPypeline to migrate to the new function name & list known repositories that will need updating~

**Comment by Chris-Schnaufer** [comment]
@Chris-Schnaufer Look into the status of this issue

**Comment by Chris-Schnaufer** [comment]
This is part of PR: https://github.com/AgPipeline/agpypeline/pull/13

An issue to update the other repo's after a new library is released needs to be made

**Comment by Chris-Schnaufer** [comment]
This change has been merged. Additional tickets will be written for downstream repos affected by this change
