### ISSUE TITLE
Add integration test to OpenDroneMap transformer using CI

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#223]
**Task to do**
Add testing to OpenDroneMap transformer for quality check for master, develop, and pull requests

**Reason**
Better transformers

**Result**
Testing occurs for master, develop, and PR changes

**Steps to take**
- [ ] Identify dataset for testing
- [ ] Build and run OpenDroneMap transformer
- [ ] Ensure results are correct

**Comment by Chris-Schnaufer** [comment]
This is pending on a better dataset becoming available - the current dataset produces variable results due to how ODM creates Orthomosaic images
