### ISSUE TITLE
Create unit and integration tests for Soil Mask, Plot Clip, Canopy Cover, and Greenness index transformers

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#235]
**Task to do**
Develop unit and integration testing and GitHub workflows for the following transformers: Soil Mask, Plot Clip, Canopy Cover, and Greenness index. This does not include Docker builds and testing

**Reason**
Unit and integration testing is good for catching changes in libraries and outside code used

**Result**
Automated testing for the identified code bases

**Results**
- [x] unit tests for transformer python code
  * [x] Soil Mask
  * [x] Plot Clip
  * [x] Canopy Cover
  * [x] Greenness indices 
- [x] integration tests for python code
- [x] python code tests automated. with GitHub workflows for develop and main branches: PRs and Merges

**Comment by Chris-Schnaufer** [comment]
Plot clip: https://github.com/AgPipeline/transformer-plotclip/pull/16
Soil mask: https://github.com/AgPipeline/transformer-soilmask/pull/19
Canopy Cover: https://github.com/AgPipeline/transformer-canopycover/pull/22
RGB Indicies: https://github.com/AgPipeline/transformer-rgb-indices/pull/9
