### ISSUE TITLE
Fix up tests in Canopy Cover transformer repository

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#244]
**Task to do**
The current canopycover_test.py file is in the root folder, as is the testing data. These need to be moved to a "tests" folder. Data that can be pulled from elsewhere should not be part of the repo. Data files can also be stored in a "test_data" folder. Make testing part of GitHub workflow

**Reason**
Have testing follow agreed upon format: *(crossed out items were already done)*
- ~~test files go in a subfolder named `tests`~~
- large testing data files should be pulled down as needed as part of the testing process (reduces what's pulled down when checking out repo)
- ~~automated testing for PR and merges~~

**Result**
The testing of this repository follows the others

**This is done when** * (crossed out items were already done)*
- [ ] ~~Files are moved to `tests` sub-folder~~
- [ ] Files that can be fetched are not part of the repo
- [ ] ~~GitHub workflow runs testing on PR and merge for develop and main branches~~
- [ ] Documentation is updated to include testing steps (such as pulling down testing files)

See the "tests", "test_data", and ".github" folders at https://github.com/AgPipeline/transformer-soilmask

**Comment by Chris-Schnaufer** [comment]
The test data files are pretty small so no download needed. Made some small changes to the YAML script.

**Comment by Chris-Schnaufer** [comment]
PR: https://github.com/AgPipeline/transformer-canopycover/pull/24
