### ISSUE TITLE
When running the SciF short workflow empty plot folders are generated

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#245]
**Task to do**

* [ ] Investigate the cause of the clipped directories for plots 1025-1032 being empty. Don't create the folders if there's nothing there to work with
* [ ] workflow should not return empty folders.
* [ ] write a test, throw exception

**Reason**
https://github.com/AgPipeline/drone-makeflow/pull/4/files#r470242326

**Result**
The cause of empty directories is resolved

**Comment by Chris-Schnaufer** [comment]
PR: https://github.com/AgPipeline/transformer-plotclip/pull/18
