### ISSUE TITLE
Update DPP Roadmap

### ISSUE THREAD

**Issue by dlebauer** [AgPipeline/computing-pipeline#270]
* [ ] Review open issues
* [ ] Review meeting notes and create new issues where necessary
* [ ] Connect issues to Epics 
* [ ] Create milestones and epics in Zenhub
* [ ] Update roadmap on OSF Wiki https://osf.io/xdkcy/wiki/Requirements/

This will be complete when we have an active roadmap including beta and v1.0 milestones in Zenhub.
