### ISSUE TITLE
Added value checks to GitHub testing actions

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#335]
**Task to do**
Add binary, text, and CSV checks to GitHib actions 

**Reason**
There currently are quantity checks for results, but this doesn't check that the result values are changing. We need to check that values are consistent (as defined/determined)

**Result**
Ability to catch diverging result values

Repos impacted:
- [x] Soil mask (https://github.com/AgPipeline/transformer-soilmask)
- [x] Plot Clip (https://github.com/AgPipeline/transformer-plotclip)
- [ ] Canopy Cover (https://github.com/AgPipeline/transformer-canopycover)
- [x] RGB Indices (https://github.com/AgPipeline/transformer-rgb-indices)

**Comment by Chris-Schnaufer** [comment]
Soil mask: https://github.com/AgPipeline/transformer-soilmask/pull/29
Plot clip: https://github.com/AgPipeline/transformer-plotclip/pull/27
Canopy Cover: https://github.com/AgPipeline/transformer-canopycover/pull/34
RGB indices: https://github.com/AgPipeline/transformer-rgb-indices/pull/20
