### ISSUE TITLE
Update base docker images to Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#380]
**Task to do**
1. Update Docker build commands to use Ubuntu 20.04 LTS
2. Update to use default Python 3.8.* if not installed

**Reason**
Ubuntu 20.04 will be used by GitHub actions: https://github.com/actions/virtual-environments/issues/1816

**Result**
Will be using newest version of Ubuntu

**Steps to take**
- [ ] Build Docker images using Ubuntu 20.04 LTS and Python 3.8.*
- [ ] Test using Docker images
- [ ] Test GitHub actions using Ubuntu 20.04
- [ ] Make new Docker images available on DockerHub after bumping image version number

**Other**
- This is not expected to require any code changes (Python, script, etc.)
- If code changes are needed, a tag in source control should be created (supplanted if a tag for non-code changes is desire)

**Comment by Chris-Schnaufer** [comment]
Pending upon updated AgPypeline library
