### ISSUE TITLE
Use Python virtual environments for SciF docker image

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#384]
**Task to do**
Move off Conda to virtual environments to reduce the size of the Docker images (12Gb at this time)

**Reason**
The docker images are getting extremely large. Using virtual environments will reduce the size

**Result**
Updated recipes for building Docker image

**Steps to take**
- [x] Install common packages to a central area (such as gdal)
- [x] Update recipes to use virtual environments
- [x] Test the resulting docker image
