### ISSUE TITLE
Review Cookie Cutter approach for template-rgb-plot

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#399]
**Task to do**
Review cookie cutter approach in https://github.com/AgPipeline/template-rgb-plot/pull/14

**Reason**
Determine:
- [ ] Is the implementation solid, or are the changes that must to be made
- [ ] Does this approach mandate cookie cutter use, or is it still flexible enough for non-cookie cutter use
- [ ] Would the approach taken to implement cookie cutters be useable for other templates

**Result**
Determination if the approach taken is solid and/or improvements must be made. If it's OK, then merge the PR. If changes need to be made, create issues to address the changes & revisit the implementation

**Comment by Chris-Schnaufer** [comment]
See https://hackmd.io/SVNHmxoZT0eYWYXLHCKCvg?view

**Comment by Chris-Schnaufer** [comment]
Julian and I have agreed to delay Cookiecutter use until there are clear benefits to be had by using it

**Comment by dlebauer** [comment]
determination was made by Chris and Julian that complexity of adding Cookie Cutter as a dependency isn't warranted. Github repo templates will provide required functionality, and will be easier for others to understand and use.
