### ISSUE TITLE
Test out SciF image on Cereus

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#406]
**Task to do**
Test SciF container on Cereus by processing data

**Reason**
Show that the SciF container works on the Cereus

**Result**
Determine confidence level regarding SciF container working on Cereus

**Apps to try**
- [ ] Soil mask (either traditional `soilmask` or `ratio_soilmask` app)
- [ ] Plot clipping
- [ ] Find files app (locates plot-clipped images and writes JSON file)
- [ ] Canopy Cover or Greenness Indices calculation

**Comment by Chris-Schnaufer** [comment]
Sample data set can be found at: https://de.cyverse.org/dl/d/3C8A23C0-F77A-4598-ADC4-874EB265F9B0/scif_test_data.tar.gz

Sample docker command lines (with a docker image named chrisatua/development:drone_makeflow), the `input` folder always contains the input files, output is places in the `output` folder, and see below for the contents of the `chris-jx-args.json` file (change as needed):
* BETYdb2GeoJson: docker run --rm -v ${PWD}/output:/output -v ${PWD}/chris-jx-args.json:/scif/apps/src/jx-args.json chrisatua/development:drone_makeflow run betydb2geojson
* shp2GeoJson: docker run --rm -v ${PWD}/inputs:/input -v ${PWD}/output:/output -v ${PWD}/chris-jx-args.json:/scif/apps/src/jx-args.json chrisatua/development:drone_makeflow run shp2geojson
* soilmask: docker run --rm -v ${PWD}/inputs:/input -v ${PWD}/output:/output -v ${PWD}/chris-jx-args.json:/scif/apps/src/jx-args.json chrisatua/development:drone_makeflow run soilmask
* plotclip: docker run --rm -v ${PWD}/inputs:/input -v ${PWD}/output:/output -v ${PWD}/chris-jx-args.json:/scif/apps/src/jx-args.json chrisatua/development:drone_makeflow run plotclip
* find_files2json: docker run --rm -v ${PWD}/inputs:/input -v ${PWD}/output:/output -v ${PWD}/chris-jx-args.json:/scif/apps/src/jx-args.json chrisatua/development:drone_makeflow run find_files2json
* canopycover: docker run --rm -v ${PWD}/inputs:/input -v ${PWD}/output:/output -v ${PWD}/chris-jx-args.json:/scif/apps/src/jx-args.json -v ${PWD}/output/canopy_cover_files.json:/scif/apps/src/canopy_cover_files.json chrisatua/development:drone_makeflow run canopycover
* greenness: docker run --rm -v ${PWD}/inputs:/input -v ${PWD}/output:/output -v ${PWD}/chris-jx-args.json:/scif/apps/src/jx-args.json -v ${PWD}/output/canopy_cover_files.json:/scif/apps/src/greenness-indices_files.json chrisatua/development:drone_makeflow run greenness-indices
* mergecsv: docker run --rm -v ${PWD}/output:/input -v ${PWD}/output:/output -v ${PWD}/chris-jx-args.json:/scif/apps/src/jx-args.json chrisatua/development:drone_makeflow run merge_csv

# chris-jx-args.json
```
{
  "BETYDB_URL": "https://terraref.ncsa.illinois.edu/bety",
  "PLOT_SHAPEFILE": "/input/plot_shapes.shp",
  "PLOT_GEOMETRY_FILE": "/output/plots.geojson",
  "SOILMASK_SOURCE_FILE": "/input/orthomosaic.tif",
  "SOILMASK_MASK_FILE": "orthomosaicmask.tif",
  "SOILMASK_WORKING_FOLDER": "/output",
  "SOILMASK_OPTIONS": "",
  "SOILMASK_RATIO_SOURCE_FILE": "/input/orthomosaic.tif",
  "SOILMASK_RATIO_MASK_FILE": "orthomosaicmask.tif",
  "SOILMASK_RATIO_WORKING_FOLDER": "/output",
  "SOILMASK_RATIO_OPTIONS": "--ratio 1.0",
  "PLOTCLIP_SOURCE_FILE": "/output/orthomosaicmask.tif",
  "PLOTCLIP_PLOTGEOMETRY_FILE": "/output/plots.geojson",
  "PLOTCLIP_WORKING_FOLDER": "/output",
  "PLOTCLIP_OPTIONS": "",
  "FILES2JSON_SEARCH_NAME": "orthomosaicmask.tif",
  "FILES2JSON_SEARCH_FOLDER": "/output",
  "FILES2JSON_JSON_FILE": "/output/canopy_cover_files.json",
  "CANOPYCOVER_OPTIONS": "",
  "GREENNESS_INDICES_OPTIONS": "",
  "MERGECSV_SOURCE": "/input",
  "MERGECSV_TARGET": "/output",
  "MERGECSV_OPTIONS": " --ignore-dirs logs,and,others "
}
```

**Comment by jvanderleeuw** [comment]
Testing worked correctly/exit codes were all 0 and the tests were able to run sequentially
