### ISSUE TITLE
Move common code for rgb-plot-base-transformer and lidar-plot-base-transformer to library

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#42]
**Task to do**
Move common code to a library that's published

**Reason**
Common sourcing plot-level code allows easier updating of dependent applications and Docker images

**Result**
A published library containing common code for plot-level algorithm bases

**Steps to take**
- [ ] Move common code to a separate library repo
- [ ] Create appropriate build environment (adding setup.py, etc.) and build library
- [ ] Publish library
- [ ] Create README.md that clearly defines the goals and details of library (such as what online library repos are supported, etc)
- [ ] Integrate with TravisCI to run pylint on code
