### ISSUE TITLE
Make videos for DPP on CyVerse

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#438]
**Task to do**
Make videos on how to use the processing pipeline on CyVerse

**Reason**
The storyboards have been created, making the videos is the next step

**Result**
A series of videos are available on YouTube AZ Digital Ag channel & have one channel for canopy cover and greenness each 

- [x] Soil Mask
- [x] Soil Mask Ratio
- [x] Plot Clip
- [x] Find Files JSON
- [x] Canopy Cover
- [x] Greenness Indices
- [x] Merge CSV
- [x] Ratio Canopy Cover

- [x] Add YouTube cards and end pages to help guide users through the playlists
