### ISSUE TITLE
Transformer template: David should be able to follow instructions

### ISSUE THREAD

**Issue by julianpistorius** [AgPipeline/computing-pipeline#470]
**Task to do**

Ensure that the transformer template (using GitHub template repo mechanism) works end-to-end.

**Reason**

Now that we're not using Cookiecutter (see https://github.com/AgPipeline/issues-and-projects/issues/399) we need to make sure that we have a single, simple mechanism for a researcher to add an algorithm.

**Result**

David can follow instructions from beginning to end

**Steps to take**

- [x] Evaluate current state of transformer template
- [x] Use simple algorithm (greenness index?) which can be modified
- [x] Ensure tests work
- [ ] Watch David complete steps

**Comment by julianpistorius** [comment]
I couldn't get all the way through because of a problem with `experiment.yml`. I was able to to basic testing.

Except for the issues below it was relatively straightforward to follow the instructions and get something going. I'd suggest @Chris-Schnaufer have a look and address whatever he thinks are worth fixing before @dlebauer tries it out.

# Evaluation

## Problem: Would be good to have examples for variables in _Definitions_ step

Possible solutions: 

- Add a link to an example transformer, like so:  
  > See example: <https://github.com/AgPipeline/transformer-rgb-indices/blob/main/algorithm_rgb.py>


## Problem: To run `generate.py` you need to install same dependencies as `algorithm_rgb.py`

- Makes it hard to start
- Defeats the purpose of using Docker

Possible solutions:

- Give instructions for using Docker to run `generate.py`
- Figure out how to parse/load the `algorithm_rgb.py` file without needing to
import its dependencies


## Problem: `generate.py` needs to be run with Python 3

Possible solutions:

- Use `python3` in the command
- Use Docker to run `generate.py` (See above)


## Problem: `test_images` should be in `.gitignore` and `.dockerignore`

Otherwise they might end up in Git and the Docker image.


## Problem: No instructions for running `testing.py` in _Test your algorithm_

Also it requires `gdal`.


## Problem: Error message about zip file when running test

```bash
docker run --rm -it -v `pwd`:/mnt --entrypoint /mnt/testing.py my_algorithm:latest /mnt/test_images
```

Output:

```
Filename,size of image channels -  (pixels),
ERROR 4: `/mnt/test_images/sample_plot_images.zip' not recognized as a supported file format.
/mnt/test_images/rgb_17_7_W.tif,7000
/mnt/test_images/rgb_40_11_W.tif,7000
/mnt/test_images/rgb_6_1_E.tif,7000
/mnt/test_images/rgb_1_2_E.tif,7000
/mnt/test_images/rgb_33_8_W.tif,7000
/mnt/test_images/rgb_5_11_W.tif,7000
```

Possible solutions:

- Delete zip file as part of instructions


## Problem: Error message about `/user/myself` when running 'production' test

```bash
docker run --rm \
  --mount "src=/user/myself,target=/mnt,type=bind" \
  my_algorithm:latest \
  --working_space "/mnt" \
  --metadata "mnt/experiment.yml" "/mnt/test_images"
```

Output:

```
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /user/myself.
See 'docker run --help'.
```

Possible solutions:

- Use environment variables or `pwd` like in prior `docker run` examples

Example using `pwd`:

```bash
docker run --rm \
  -v `pwd`:/mnt \
  my_algorithm:latest \
  --working_space "/mnt" \
  --metadata "mnt/experiment.yml" "/mnt/test_images"
```

(Also pretty sure `"mnt/experiment.yml"` should be `"mnt/experiment.yml"`)

## Problem: Error message about `/mnt/experiment.yml` when running 'production' test

```bash
docker run --rm \
    -v `pwd`:/mnt \
    my_algorithm:latest \
    --working_space "/mnt" \
    --metadata "/mnt/experiment.yml" "/mnt/test_images"
```

Output:

```
ERROR:root:Unable to access metadata file '/mnt/experiment.yml'
ERROR:root:Stopping processing
ERROR:root:Unable to access metadata file '/mnt/experiment.yml'
ERROR:root:Stopping processing
{
"error": "Unable to access metadata file '/mnt/experiment.yml'",
"code": -3
}
```

I couldn't find an `experiment.yml` in the repository, nor in
<https://github.com/AgPipeline/transformer-rgb-indices/>

**Comment by dlebauer** [comment]
next step: @Chris-Schnaufer to review then follow up w/ @Chris-Schnaufer and @julianpistorius and optionally @dlebauer

**Comment by Chris-Schnaufer** [comment]
Items not listed here have been implemented. Some comments on items that aren't being changed or can use clarification:

> Problem: To run generate.py you need to install same dependencies as algorithm_rgb.py

* This is to be expected since it's assumed that development is happening on the local machine. `datetime` is the only additional **import**, and that comes bundled with Python

> Problem: generate.py needs to be run with Python 3

* The command to run `generate.py` using Python3 on the command line will be added for those cases where the script isn't executable on the user's machine.
* Since this step is used to generate the Dockfile, using Docker to run the script creates a circular reference problem and instructions for this won't be added.

> Problem: No instructions for running testing.py in Test your algorithm

Adding instructions for `python3 testing.py` command line option. Also, changing `numpy` requirement to `PIL` which is much easier to install.

> Problem: Error message about zip file when running test

Added command to delete the zip file

> Problem: Error message about /user/myself when running 'production' test

Changed to use `${PWD}`

> Problem: Error message about /mnt/experiment.yml when running 'production' test

Removed optional `experiment.yml` parameters.

**Comment by Chris-Schnaufer** [comment]
@julianpistorius PR: https://github.com/AgPipeline/template-rgb-plot/pull/19

**Comment by dlebauer** [comment]
@julianpistorius since Python 2 is no longer supported, why is it a problem that generate.py needs to be run with Python 3?

**Comment by dlebauer** [comment]
@Chris-Schnaufer Is this ready for me to review? Where do I start?

**Comment by Chris-Schnaufer** [comment]
@dlebauer I'm waiting for Julian to review the PR

**Comment by julianpistorius** [comment]
> @dlebauer I'm waiting for Julian to review the PR

@Chris-Schnaufer & @dlebauer I've approved the PR.

David: As soon as Chris merges the PR you should be able to review it.

> @julianpistorius since Python 2 is no longer supported, why is it a problem that generate.py needs to be run with Python 3?

The problem is that people might run `python generate.py` (like I did). Depending on their local setup/operating system `python` might map to Python 2 instead of Python 3 (like on my system). If this is the case then they will get a syntax error because `generate.py` is not compatible with Python 2. By specifying `python3` explicitly on the command line it avoids this problem.

**Comment by dlebauer** [comment]
Overall I think this will be a useful approach. But it will need some user testing and feedback ... so I will kick it off ...  

- README should explain the intent of the repository (content from HOW_TO.md?)
- HOW_TO.md
    - explain what the inputs are
    - provide an example input
- Migrate to using setup.py or codemeta.json for code metadata https://github.com/AgPipeline/issues-and-projects/issues/92
- remove betydb and geostreams specific flags; replace with output argument that can have one or more output formats
- might need to add >1 citation
- what if you return a list of objects with different shapes (e.g. vector length 3 + a scalar?)
- there should be some interactive REPL dev w/ the test data ... leading to debugging and writing of unit tests
- for template, need to define dependencies (e.g. numpy, gdal)
    - gdal requires C++ build tools on windows 
    - is gdal required for testing or can it replaced by something lighter weight????
    - maybe could we point users to GitHub's new codespaces for development
- when trying to run testing.py using docker, I got the error:
>  'docker: Error response from daemon: create `pwd`: "`pwd`" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allow
ed. If you intended to pass a host directory, use absolute path.
- for the new algorithm, user needs to be instructed to define package dependencies and add citations to the README
- add checklists for each section. e.g. algorithm.py needs
    - remove / update comments
    - require typing
    - add documentation for arguments and return value 
- can the generation of requirements.txt be automated using something like `pipreqs`? https://stackoverflow.com/a/31684470/199217
- not clear if having a packages.txt file makes it easier - is this a bespoke convention?
    - I'm on Windows, so the package names don't translate; anyone not using apt repositories may have similar issues 
    - I'm not sure what the solution is, but editing the Dockerfile seems just as easy or easier (is better documented, can be debugged using standard docker commands) 
- finishing up 
    - add checklist
    - include some way of registering the new algorithm(s)
- FAQs 
    - what if I want to add many related algorithms at once, can they all be in the same repository? 

Next steps:

- [ ] review w/ David and move list above to new issues
