### ISSUE TITLE
Review testing documentation, existing tests, and define next steps

### ISSUE THREAD

**Issue by dlebauer** [AgPipeline/computing-pipeline#482]
**Task to do**

- Review transformer tests. Make sure all science algorithms are sufficiently tested
- have some test files that can be consistently used

**Reason**

Currently, the output of algorithms aren't well tested, and it isn't clear for a contributor what type of tests they should write. Our repositories should be exemplars of the good testing that is necessary to help make shared software reliable and interpretable. 

Tests like this https://github.com/AgPipeline/transformer-canopycover/blob/2ab5fc2f6e92a713b0044d833a37bb0bb8d9633f/tests/test_canopy_cover.py#L220 say 'somewhere a csv file is generated, and one of the fields contains the string '99.8'. That is an integration test, which is great to have! 

But we also want to be able to demonstrate basic tests of the algorithm output. For, e.g. five files (preferably of varying quality and / or canopy cover), the `calculate_canopycover_masked` and the `CanopyCover` functions should be tested. 

**Result**

David, Chris and Julian:

- [ ] review testing documentation 
- [ ] review existing extractor tests
- [ ] _collaboratively_ update [testing documentation wiki](https://osf.io/xdkcy/wiki/Testing/)
- [ ] create new issues for writing tests
