### ISSUE TITLE
Finish UI algorithm editor for plot-level RGB

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#497]
**Task to do**
Finish implementing algorithm writing UI

**Reason**
Allows users to develop algorithms using the UI

**Result**
Able to develop and test Algorithms (using pre-determined plot level RGB images)

**Features**
- [x] Edit fields and return values
- [x] Code linting
- [x] Run sample tests using pre-determined images                          
- [ ] ~Able to specify Git repos for adding algorithms to list and saving algorithms~

**Comment by Chris-Schnaufer** [comment]
Closing this issue and writing a new one to finish the remaining item (git integration)

**Comment by Chris-Schnaufer** [comment]
![Screen Shot 2021-06-18 at 9.49.45 AM.png](https://images.zenhubusercontent.com/5c14118eee1e975f1842e1c2/2a3c8748-826a-4918-b446-eca1abb2b75a)![Screen Shot 2021-06-18 at 9.50.17 AM.png](https://images.zenhubusercontent.com/5c14118eee1e975f1842e1c2/ae7c302c-81c4-4c2b-a95a-b52972b3e3ea)
