### ISSUE TITLE
Update drone-workflow repo to pull latest versions of transformers

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#504]
**Task to do**
Update the recipes to pull the latest versions of transformers

**Reason**
Keep the recipes up to date with the latest changes

**Result**
Recipes are updated

**Transformers with new versions**
- [x] transformer-soilmask v2.4
- [x] transformer-soilmask-by-ratio v1.2
- [x] transformer-canopycover v1.8
- [x] plot-base-rgb v1.10 (used by transformer-rgb-indices)
- [x] transformer-rgb-indices v1.4

Also, update the following:
- [x] Merge CSV (allows specifying one output file): /iplant/home/schnaufer/merge_csv.py on CyVerse
