### ISSUE TITLE
Fix GitHub Actions that are failing

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#539]
**Task to do**
Fix failing GitHub Actions

**Reason**
Due to changes to pylint, Actions are failing
Some Docker testing is failing as well

**Result**
GitHub actions can successfully run to completion without any errors

**Repositories**
- [x] transformer-soilmask
- [x] transform-opendronemap
- [x] plot-base-rgb
- [x] transformer-soilmask-by-ratio
- [x] transformer-canopycover
- [x] template-transformer-simple
- [x] agpypeline
- [x] transformer-plotclip
- [x] drone-makeflow
