### ISSUE TITLE
Fix GitHub action issues

### ISSUE THREAD

**Issue by Chris-Schnaufer** [AgPipeline/computing-pipeline#553]
**Task to do**
GitHub actions are failing

**Reason**
GitHub actions should be working

**Result**
GitHub actions successfully tun again

**Repositories**
- [x] plot-base-rgb
- [x] transformer-opendronemap
- [x] transformer-soilmask
- [x] agpypeline (build is not failing, updated needed for downstream dependencies)
- [x] transformer-canopycover
- [x] transformer-soilmask-by-ratio
- [x] template-transformer-simple
- [x] drone-makeflow
- [x] transformer-plotclip
- [x] transformer-rgb-indices
- [x] template-rgb-plot

**Comment by Chris-Schnaufer** [comment]
These build failures appear to be related to setuptools: github.com/pypa/setuptools/issues/2781
