### ISSUE TITLE
IRODS ingestion of gantry data (continue 02)

### ISSUE THREAD

**Issue by julianpistorius** [AgPipeline/computing-pipeline#93]
Continuation of https://github.com/AgPipeline/issues-and-projects/issues/82

**Task to do**

Set up and document an automated process for ingesting gantry data into CyVerse Data Store (IRODS)

**Reason**

- [ ] Ease of access from VICE (for workbench/data exploration)
- [ ] Close to CyVerse & UA computational resources

**Result**

- Scripts and configuration necessary for setting this up
- Document (as text file in the code repository where the automation & logic end up)
- Monitoring & alerting (at least documenting what success/failure looks like)

**Steps to take**

- [ ] Ensure tar file creation & `irsync` work reliably (or fail noisily)

**Comment by julianpistorius** [comment]
See https://github.com/az-digitalag/organization/issues/177 - it should take the guess work out of knowing when it's OK to tar up the files for a scan (assuming we also know whether we have all the files for a scan.)

**Comment by julianpistorius** [comment]
The manually-triggered batch process failed because at least one of the tar files was bigger than 900GB and filled the drive used for intermediate artifacts.

Will have to figure out a workaround.

Options:

- Create tar in a different location
- Create a separate tar for each 'image' (aka the directory with raw data and metadata for each 'snapshot')
- ???

**Comment by julianpistorius** [comment]
- [ ] @dlebauer to ask for a 4 TB SSD to be installed in ds06 (fieldscanner-data.arizona.edu): <https://github.com/AgPipeline/issues-and-projects/issues/115>

**Comment by julianpistorius** [comment]
Continued in https://github.com/AgPipeline/issues-and-projects/issues/116
